name: is_first_run
description: A simple package to check if it is the first time the app runs.
version: 0.1.0
repository: https://github.com/JulianAssmann/flutter_is_first_run
homepage: https://julianassmann.de

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: